### ISSUE TITLE
ProxyObject._pyroTimeout behavior

### ISSUE THREAD

**Issue by emruiz81** [irmen/Pyro4#172] opened 2017-05-04 23:08 UTC
Hi,

I'm trying to use the ._pyroTimeout attribute in my client/server implementation. The problem I'm experiencing is that when a timeout occurs in the server (for calling a blocking method), an exception is thrown in the client (which is OK), but then the server ends its requestLoop().
My question is: What happens if other objects were working from separate client threads? Is this the expected behavior?, what I think should be more useful is to report the timeout exception in the client thread that called that blocking method (as it is happening right now), but at least give some time to the other threads to end their jobs (in case they were working on something else). 
The thing is, I whish I could catch timeouts per session, without affecting other sessions.

Thanks in advance for your help! 
This API is one of the most fantastic Python libs I've ever seen! (and trust me, I've been working with Python for years :) ).

Regards,

Ezequiel

**Comment by irmen** [comment] 2017-05-05 21:45
Hi,
what do you mean exactly with "the server ends its requestloop?"   Is it crashing? what is the traceback if so? Or is it simply stopping and exiting?

Setting the _pyroTimeout on a proxy is only for the client socket connection of that particular proxy.
Any other connections should not notice anything from it.

thanks for the feedback I'm happy to hear you like Pyro a lot.

**Comment by irmen** [comment] 2017-05-10 17:30
Have you been able to resolve your  problem or do you need more assistance? If so, please provide a minimal piece of example code exhibiting your issue.

**Comment by irmen** [comment] 2017-05-15 17:42
@emruiz81 I'll close this issue as cannot reproduce for now. If you're still working on it feel free to comment again but do provide some more details.

**Closed by irmen** 2017-05-15 17:42 UTC
